title: Pokemon Snowfall
description: A Pokemon Emerald hack set fifteen years into the future
theme: just-the-docs

url: https://lorissa-b.github.io/pokesnowfall

heading_anchors: true

collections:
  routes:
    output: true

just_the_docs:
  collections:
    routes:
      name: Routes, Cities & Landmarks
      nav_fold: true
